source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'DelivaryRobot' do
    pod 'SwiftyJSON'
    pod 'Alamofire', '~> 3.4'
    pod 'DZNEmptyDataSet'
    pod 'RAMAnimatedTabBarController'
    pod 'SCLAlertView'
    pod 'CryptoSwift'
    pod 'EVReflection'
    pod 'CocoaMQTT'
    pod 'IQKeyboardManagerSwift'
end
